[package]
name = "lua_minifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lua_parser = { git = "https://github.com/PY44N/LuaParser" }